# Projet Machine Learning

### Partie 1 : Collecte des données

On va importer les données de la liste des passagers du Titanic via Kaggle

In [16]:
from pathlib import Path
import urllib.request
import os 
import pandas as pd

def github_data(file_path):
    csv_path=Path(f"datasets/{file_path}")
    if not csv_path.is_file():
        Path("datasets").mkdir(parents=True, exist_ok=True)
        url=f"https://raw.githubusercontent.com/dariusbengo/prediction-de-survie-aux-naufrages/main/{file_path}"
        urllib.request.urlretrieve(url,csv_path)
    return pd.read_csv(csv_path)


titanic=github_data("Titanic-Dataset.csv")
lusitania=github_data("RMS%20Lusitania%20-%20Sheet1.csv")
estonia= github_data("estonia-passenger-list.csv")

On explore les bases de données

In [7]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:

age_inconnu=titanic["Age"].isna().sum()/titanic["Age"].count()
print("Il y a", f"{age_inconnu:1%}", "de personnes ayant un age inconnu" )

0.24789915966386555
Il y a 24.789916% de personnes ayant un age inconnu

In [60]:
titanic1=titanic[["Survived","Pclass","Sex", "Age", "SibSp","Parch","Fare"]]
titanic1

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0           0       3    male  22.0      1      0   7.2500
1           1       1  female  38.0      1      0  71.2833
2           1       3  female  26.0      0      0   7.9250
3           1       1  female  35.0      1      0  53.1000
4           0       3    male  35.0      0      0   8.0500
..        ...     ...     ...   ...    ...    ...      ...
886         0       2    male  27.0      0      0  13.0000
887         1       1  female  19.0      0      0  30.0000
888         0       3  female   NaN      1      2  23.4500
889         1       1    male  26.0      0      0  30.0000
890         0       3    male  32.0      0      0   7.7500

[891 rows x 7 columns]

Dans la base de données des passagers du Titanic, il y a 12 colonnes. Plusieurs vont retenir notre attention pour essayer de déterminer la probabilité de survivre à un naufrage:
 La variable `Survived` qui sera notre variable prédite (1 si le passager a survécu, 0 sinon),
  les variables `Pclass` (classe dans le bateau),
   `sex`, 
   `age`, 
   `SibSp` (nombre de frères et soeurs et/ou de conjoints), 
   `Parch` (nombre de parents et/ou enfants présents dans le bateau) 
   et  `Fare` (prix du ticket) qui seront des variables explicatives.

In [17]:
lusitania

,Family name,Title,Personal name,Fate,Age,Department/Class,Passenger/Crew,Citizenship,Position,Status,...,Country,Lifeboat,Rescue Vessel,Body No.,Ticket No.,Cabin No.,Traveling Companions and other notes,Value,Adult/Minor,Sex
0,CAMERON,Mr.,Charles W.,Lost,38,Band,Crew,British,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult,Male
1,CARR-JONES,Mr.,E.,Lost,37,Band,Crew,British,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult,Male
2,DRAKEFORD,Mr.,Edward,Saved,30,Band,Crew,British,Violin,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult,Male
3,HAWKINS,Mr.,Handel,Saved,25,Band,Crew,British,Cello,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult,Male
4,HEMINGWAY,Mr.,John William,Saved,27,Band,Crew,British,Double Bass,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1956,WOOD,Mr.,Alfred,Saved,NaN,Victualling,Crew,British,Saloon Cabin Bed Steward,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult,Male
1957,WOOD,Mr.,Wallace Edkin,Lost,NaN,Victualling,Crew,British,"Barkeeper, Smokeroom Second Cabin",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult,Male
1958,WRIGHT,Master (?),Harold Joseph,Lost,NaN,Victualling,Crew,British,Steward's Boy,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Minor?,Male
1959,WYNNE,Master,George,Saved,16,Victualling,Crew,British,Assistant Cook,NaN,...,England,14,Indian Empire,NaN,NaN,NaN,George was assistant cook in first class. Age ...,1,Minor,Male
1960,WYNNE,Mr.,Joseph Dominic,Lost,37,Victualling,Crew,British,Sculleryman,NaN,...,England,NaN,NaN,NaN,NaN,NaN,Joseph was George’s father. Suffered from bron...,1,Adult,Male

In [18]:
estonia

,PassengerId,Country,Firstname,Lastname,Sex,Age,Category,Survived
0,1,Sweden,ARVID KALLE,AADLI,M,62,P,0
1,2,Estonia,LEA,AALISTE,F,22,C,0
2,3,Estonia,AIRI,AAVASTE,F,21,C,0
3,4,Sweden,JURI,AAVIK,M,53,C,0
4,5,Sweden,BRITTA ELISABET,AHLSTROM,F,55,P,0
...,...,...,...,...,...,...,...,...
984,985,Sweden,ANNA INGRID BIRGITTA,OSTROM,F,60,P,0
985,986,Sweden,ELMAR MIKAEL,OUN,M,34,P,1
986,987,Sweden,ENN,QUNAPUU,M,77,P,0
987,988,Sweden,LY,GUNAPUU,F,87,P,0
988,989,Sweden,CARL,OVBERG,M,42,P,1

Transformations à effectuer sur titanic : mettre en sex en binaire, verifier si les ages sont en chiffres pour ceux qui ont moins d'1 an, on ne peut pas vraiment remplacer na par moyenne pour l'age car la distribution est elargie, il y a des noveaux nés comme des vieux, ca pourrait fausser la dsitrib, il fay a un 1/4 des observations ou l'age est inconnu


mettre les sexes sur le meme label